# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: beman-submodule tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  beman-submodule-script-ci:
    name: beman_module.py ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install pytest
        run: |
          python3 -m pip install pytest

      - name: Run pytest
        run: |
          cd tools/beman-submodule/
          pytest
