# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: 'Beman preset test matrix'
on:
  workflow_call:
    inputs:
      matrix_config:
        description: 'JSON array of {preset:"", runner:""} or {preset:"", image:""} objects'
        type: string
        required: true
jobs:
  preset_test_matrix:
    strategy:
      fail-fast: false
      matrix:
        presets: ${{ fromJSON(inputs.matrix_config) }}
    name: "Preset: ${{ matrix.presets.preset }} on ${{ matrix.presets.runner || 'ubuntu-latest' }}"
    runs-on: ${{ matrix.presets.runner || 'ubuntu-latest' }}
    container: ${{ matrix.presets.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup build environment
        if: matrix.presets.runner
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "4.0.3"
          ninjaVersion: "1.13.0"
      - name: Setup MSVC
        if: startsWith(matrix.presets.runner, 'windows')
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Run preset
        run: cmake --workflow --preset ${{ matrix.presets.preset }}
